--- !ruby/object:Library
authors:
- &1 !ruby/object:Author
  name: Dan Brown
  biography: Bio1
- &2 !ruby/object:Author
  name: Joanne Rowling
  biography: Bio
- &3 !ruby/object:Author
  name: A.C. Doyle
  biography: Bio
- &4 !ruby/object:Author
  name: Chuck Palahniuk
  biography: bio
books:
- &5 !ruby/object:Book
  title: Da Vinci Code
  author: *1
- &9 !ruby/object:Book
  title: Origin
  author: *1
- &8 !ruby/object:Book
  title: Inferno
  author: *1
- !ruby/object:Book
  title: Harry Potter and the Philosopher's Stone
  author: *2
- !ruby/object:Book
  title: Harry Potter and the Chamber of Secrets
  author: *2
- !ruby/object:Book
  title: Harry Potter and the Prisoner of Azkaban
  author: *2
- !ruby/object:Book
  title: Gelseminum as a poison
  author: *3
- !ruby/object:Book
  title: A Scandal in Bohemia
  author: *3
- &10 !ruby/object:Book
  title: The Green Flag
  author: *3
- &11 !ruby/object:Book
  title: Fight club
  author: *4
readers:
- &6 !ruby/object:Reader
  name: DK
  email: dk@gmail.com
  city: D
  street: street
  house: 1
- &7 !ruby/object:Reader
  name: DM
  email: dk@gmail.com
  city: D
  street: street
  house: 1
- !ruby/object:Reader
  name: DS
  email: dk@gmail.com
  city: D
  street: street
  house: 1
- &12 !ruby/object:Reader
  name: DT
  email: dk@gmail.com
  city: D
  street: street
  house: 1
orders:
- !ruby/object:Order
  book: *5
  reader: *6
  date: 2020-12-20 12:23:53.264008449 +02:00
- !ruby/object:Order
  book: *5
  reader: *7
  date: 2020-12-20 12:23:53.264013160 +02:00
- !ruby/object:Order
  book: *5
  reader: *7
  date: 2020-12-20 12:23:53.264015427 +02:00
- !ruby/object:Order
  book: *8
  reader: *6
  date: 2020-12-20 12:23:53.264017233 +02:00
- !ruby/object:Order
  book: *9
  reader: *6
  date: 2020-12-20 12:23:53.264018877 +02:00
- !ruby/object:Order
  book: *9
  reader: *7
  date: 2020-12-20 12:23:53.264020482 +02:00
- !ruby/object:Order
  book: *8
  reader: *7
  date: 2020-12-20 12:23:53.264022120 +02:00
- !ruby/object:Order
  book: *10
  reader: *6
  date: 2020-12-20 12:23:53.264023615 +02:00
- !ruby/object:Order
  book: *11
  reader: *12
  date: 2020-12-20 12:23:53.268759535 +02:00
